#!/usr/bin/env python
#
#  ARRANGEMUSIC.py
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <mo@liberejo.de> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return - Remo Giermann.
# ----------------------------------------------------------------------------
#
# create hierarchical directory structure of music files based on tag information.
#

import os, sys
import tagpy
from arrangemusic_tools import config, processing

options, sources = processing.start(sys.argv[1:], tagpy.FileRef)

try:
	for s in sources:
		processing.process_file(s, options)
		
except KeyboardInterrupt:
	print "\nTerminating..."